export const ADD_INGREDIENTE = 'ADD_INGREDIENTE';
export const REMOVE_INGREDIENTE = 'REMOVE_INGREDIENTE';
export const INITIALIZE_INGREDIENTS = 'INITIALIZE_INGREDIENTS';
export const SET_ERROR = 'SET_ERROR';