export const BEGIN_ORDER = 'BEGIN_ORDER';
export const ORDER_PLACED_SUCCESFULLY = 'ORDER_PLACED_SUCCESFULLY';
export const ORDER_PLACED_ERROR = 'ORDER_PLACED_ERROR';
export const LOAD_ORDERS_START = 'LOAD_ORDERS_START';
export const LOAD_ORDERS_SUCESS = 'LOAD_ORDERS_SUCESS'
export const LOAD_ORDERS_FAIL = 'LOAD_ORDERS_FAIL';